In [11]:
import pandas as pd

PLAY_STORE_FILE = "play Store Data.csv.xlsx"

apps = pd.read_excel(PLAY_STORE_FILE)

print("Dataset loaded successfully!")
print("Shape:", apps.shape)
print("\nColumns:")
print(apps.columns.tolist())

Dataset loaded successfully!
Shape: (10841, 13)

Columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [9]:
import pandas as pd

PLAY_STORE_FILE = "play Store Data.csv.xlsx"

apps = pd.read_excel(PLAY_STORE_FILE)

print("Dataset loaded successfully!")
print("Shape:", apps.shape)
print("\nColumns:")
print(apps.columns.tolist())

Dataset loaded successfully!
Shape: (10841, 13)

Columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

In [10]:
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [12]:
# Check dataset structure
print("Number of rows:", len(apps))
print("Number of columns:", len(apps.columns))
print("\nColumn names:")
for i, col in enumerate(apps.columns, 1):
    print(i, ":", col)

Number of rows: 10841
Number of columns: 13

Column names:
1 : App
2 : Category
3 : Rating
4 : Reviews
5 : Size
6 : Installs
7 : Type
8 : Price
9 : Content Rating
10 : Genres
11 : Last Updated
12 : Current Ver
13 : Android Ver

In [13]:
# Check missing values and data types

print("DATA TYPES:")
print(apps.dtypes)

print("\nMISSING VALUES:")
print(apps.isnull().sum())

DATA TYPES:
App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

MISSING VALUES:
App                  1
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [14]:
# Check for duplicate records

duplicate_count = apps.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 483

In [15]:
# Remove duplicate rows

before = len(apps)

apps = apps.drop_duplicates().copy()

after = len(apps)

print("Rows before removing duplicates:", before)
print("Duplicate rows removed:", before - after)
print("Rows after removing duplicates:", after)

Rows before removing duplicates: 10841
Duplicate rows removed: 483
Rows after removing duplicates: 10358

In [16]:
# Clean and convert numeric columns

# Reviews
apps["Reviews"] = pd.to_numeric(apps["Reviews"], errors="coerce")

# Installs: remove '+' and ',' and convert to numeric
apps["Installs"] = (
    apps["Installs"]
    .astype(str)
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)
apps["Installs"] = pd.to_numeric(apps["Installs"], errors="coerce")

# Size: convert MB/GB values to MB
def convert_size(value):
    if pd.isna(value):
        return None

    value = str(value).strip()

    if value.endswith("M"):
        return float(value[:-1])

    if value.endswith("k"):
        return float(value[:-1]) / 1024

    if value.endswith("G"):
        return float(value[:-1]) * 1024

    return None

apps["Size_MB"] = apps["Size"].apply(convert_size)

# Price: remove '$' and convert to numeric
apps["Price"] = (
    apps["Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
)
apps["Price"] = pd.to_numeric(apps["Price"], errors="coerce")

print("Numeric columns cleaned successfully.")
print("\nData types after cleaning:")
print(apps[["Reviews", "Installs", "Size_MB", "Price"]].dtypes)

Numeric columns cleaned successfully.

Data types after cleaning:
Reviews     float64
Installs    float64
Size_MB     float64
Price       float64
dtype: object

In [17]:
# Check missing values after numeric conversion

print("Missing values after cleaning:")
print(apps[["Reviews", "Installs", "Size_MB", "Price"]].isnull().sum())

Missing values after cleaning:
Reviews        1
Installs       1
Size_MB     1527
Price          1
dtype: int64

In [18]:
# Inspect rows with missing numeric values

print("Rows with missing Reviews:")
print(apps[apps["Reviews"].isna()][["App", "Category", "Reviews", "Installs", "Size", "Price"]])

print("\nRows with missing Installs:")
print(apps[apps["Installs"].isna()][["App", "Category", "Reviews", "Installs", "Size", "Price"]])

print("\nRows with missing Price:")
print(apps[apps["Price"].isna()][["App", "Category", "Reviews", "Installs", "Size", "Price"]])

Rows with missing Reviews:
                                           App Category  Reviews  Installs  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9      NaN       NaN

         Size  Price
10472  1,000+    NaN

Rows with missing Installs:
                                           App Category  Reviews  Installs  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9      NaN       NaN

         Size  Price
10472  1,000+    NaN

Rows with missing Price:
                                           App Category  Reviews  Installs  \
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9      NaN       NaN

         Size  Price
10472  1,000+    NaN

In [19]:
# Remove the row with missing critical numeric values

before = len(apps)

apps = apps.dropna(subset=["Reviews", "Installs", "Price"]).copy()

after = len(apps)

print("Missing-value rows removed:", before - after)
print("Rows before:", before)
print("Rows after:", after)

print("\nRemaining missing values:")
print(apps[["Reviews", "Installs", "Size_MB", "Price"]].isna().sum())

Missing-value rows removed: 1
Rows before: 10358
Rows after: 10357

Remaining missing values:
Reviews        0
Installs       0
Size_MB     1526
Price          0
dtype: int64

In [20]:
# Clean text columns

text_columns = ["App", "Category", "Type", "Content Rating", "Genres"]

for col in text_columns:
    apps[col] = apps[col].astype(str).str.strip()

print("Text columns cleaned successfully.")

print("\nMissing values in important columns:")
print(apps[text_columns].isna().sum())

Text columns cleaned successfully.

Missing values in important columns:
App               0
Category          0
Type              0
Content Rating    0
Genres            0
dtype: int64

In [21]:
# Clean Last Updated and Android Version columns

# Convert Last Updated to datetime
apps["Last Updated"] = pd.to_datetime(
    apps["Last Updated"],
    errors="coerce"
)

# Clean Android Version
apps["Android Ver"] = (
    apps["Android Ver"]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
)

apps["Android Ver"] = pd.to_numeric(
    apps["Android Ver"],
    errors="coerce"
)

print("Date and Android Version columns cleaned successfully.")

print("\nData types:")
print(apps[["Last Updated", "Android Ver"]].dtypes)

print("\nMissing values:")
print(apps[["Last Updated", "Android Ver"]].isna().sum())

Date and Android Version columns cleaned successfully.

Data types:
Last Updated    datetime64[ns]
Android Ver            float64
dtype: object

Missing values:
Last Updated       0
Android Ver     1223
dtype: int64

In [22]:
# Restore actual missing values that became the text "nan"

text_columns = ["App", "Category", "Type", "Content Rating", "Genres"]

for col in text_columns:
    apps[col] = apps[col].replace("nan", pd.NA)

print("Missing values after correction:")
print(apps[text_columns].isna().sum())

Missing values after correction:
App               1
Category          0
Type              1
Content Rating    0
Genres            0
dtype: int64

In [23]:
# Remove rows missing essential categorical information

before = len(apps)

apps = apps.dropna(
    subset=["App", "Category", "Type", "Content Rating"]
).copy()

after = len(apps)

print("Rows removed:", before - after)
print("Rows remaining:", after)

print("\nRemaining missing values:")
print(apps[["App", "Category", "Type", "Content Rating", "Genres"]].isna().sum())

Rows removed: 2
Rows remaining: 10355

Remaining missing values:
App               0
Category          0
Type              0
Content Rating    0
Genres            0
dtype: int64

In [24]:
# Final dataset validation

print("FINAL DATASET SUMMARY")
print("=" * 40)

print("Rows:", apps.shape[0])
print("Columns:", apps.shape[1])

print("\nData types:")
print(apps.dtypes)

print("\nMissing values:")
print(apps.isna().sum())

print("\nDuplicate rows:")
print(apps.duplicated().sum())

FINAL DATASET SUMMARY
========================================
Rows: 10355
Columns: 14

Data types:
App                       object
Category                  object
Rating                   float64
Reviews                  float64
Size                      object
Installs                 float64
Type                      object
Price                    float64
Content Rating            object
Genres                    object
Last Updated      datetime64[ns]
Current Ver               object
Android Ver              float64
Size_MB                  float64
dtype: object

Missing values:
App                  0
Category             0
Rating            1464
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver       1222
Size_MB           1525
dtype: int64

Duplicate rows:
0

In [25]:
# ============================================================
# TASK 1 — BUBBLE CHART
# Load User Reviews dataset
# ============================================================

USER_REVIEWS_FILE = "User Reviews.csv"

reviews = pd.read_csv(USER_REVIEWS_FILE)

print("User Reviews Dataset loaded successfully!")
print("Shape:", reviews.shape)

print("\nColumns:")
print(reviews.columns.tolist())

print("\nFirst 5 rows:")
display(reviews.head())

User Reviews Dataset loaded successfully!
Shape: (64295, 5)

Columns:
['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity', 'Sentiment_Subjectivity']

First 5 rows:

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [26]:
# ============================================================
# TASK 1 — PREPARE SENTIMENT SUBJECTIVITY
# Calculate average subjectivity for each app
# ============================================================

app_subjectivity = (
    reviews
    .dropna(subset=["Sentiment_Subjectivity"])
    .groupby("App", as_index=False)["Sentiment_Subjectivity"]
    .mean()
    .rename(columns={
        "Sentiment_Subjectivity": "Avg_Subjectivity"
    })
)

print("Average subjectivity calculated successfully.")

print("Number of apps with subjectivity data:", len(app_subjectivity))

print("\nFirst 5 results:")
display(app_subjectivity.head())

Average subjectivity calculated successfully.
Number of apps with subjectivity data: 865

First 5 results:

                                App  Avg_Subjectivity
0             10 Best Foods for You          0.495455
1  104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室          0.545516
2                              11st          0.443957
3        1800 Contacts - Lens Store          0.591098
4   1LINE – One Line with One Touch          0.557315

In [27]:
# ============================================================
# TASK 1 — MERGE SUBJECTIVITY WITH PLAY STORE DATA
# ============================================================

task1_data = apps.merge(
    app_subjectivity,
    on="App",
    how="left"
)

print("Task 1 datasets merged successfully!")

print("Rows:", task1_data.shape[0])
print("Columns:", task1_data.shape[1])

print("\nSubjectivity missing values:")
print(task1_data["Avg_Subjectivity"].isna().sum())

print("\nSample of merged data:")
display(
    task1_data[
        ["App", "Category", "Rating", "Reviews",
         "Size_MB", "Installs", "Avg_Subjectivity"]
    ].head()
)

Task 1 datasets merged successfully!
Rows: 10355
Columns: 15

Subjectivity missing values:
9341

Sample of merged data:

,App,Category,Rating,Reviews,Size_MB,Installs,Avg_Subjectivity
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,NaN
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,0.64154
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,NaN
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,NaN
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,NaN

In [28]:
# ============================================================
# TASK 1 — CHECK APP NAME MATCHING
# ============================================================

play_store_apps = set(apps["App"].dropna().unique())
review_apps = set(reviews["App"].dropna().unique())

matched_apps = play_store_apps.intersection(review_apps)

print("Unique Play Store apps:", len(play_store_apps))
print("Unique Review apps:", len(review_apps))
print("Matching app names:", len(matched_apps))

print("\nPlay Store apps without review data:",
      len(play_store_apps - review_apps))

print("Review apps not in Play Store:",
      len(review_apps - play_store_apps))

Unique Play Store apps: 9657
Unique Review apps: 1074
Matching app names: 959

Play Store apps without review data: 8698
Review apps not in Play Store: 115

In [29]:
# ============================================================
# TASK 1 — APPLY ALL REQUIRED FILTERS
# ============================================================

allowed_categories = [
    "GAME",
    "BEAUTY",
    "BUSINESS",
    "COMICS",
    "COMMUNICATION",
    "DATING",
    "ENTERTAINMENT",
    "SOCIAL",
    "EVENTS"
]

task1_data = task1_data[
    # Rating > 3.5
    (task1_data["Rating"] > 3.5)

    # Required categories
    & (task1_data["Category"].isin(allowed_categories))

    # Reviews > 500
    & (task1_data["Reviews"] > 500)

    # Installs > 50K
    & (task1_data["Installs"] > 50000)

    # App name must not start with X, Y or Z
    & (~task1_data["App"].str.lower().str.startswith(
        ("x", "y", "z"), na=False
    ))

    # App name must not contain the letter S
    & (~task1_data["App"].str.lower().str.contains(
        "s", na=False
    ))

    # Sentiment subjectivity > 0.5
    & (task1_data["Avg_Subjectivity"] > 0.5)

    # Size must be available for the X-axis
    & (task1_data["Size_MB"].notna())
].copy()

print("Task 1 filtered rows:", len(task1_data))

print("\nCategories remaining:")
print(task1_data["Category"].value_counts())

print("\nMissing values in required chart columns:")
print(
    task1_data[
        ["App", "Category", "Size_MB", "Rating",
         "Installs", "Reviews", "Avg_Subjectivity"]
    ].isna().sum()
)

Task 1 filtered rows: 33

Categories remaining:
Category
GAME             19
DATING            5
COMMUNICATION     4
BUSINESS          2
ENTERTAINMENT     2
SOCIAL            1
Name: count, dtype: int64

Missing values in required chart columns:
App                 0
Category            0
Size_MB             0
Rating              0
Installs            0
Reviews             0
Avg_Subjectivity    0
dtype: int64

In [44]:
# ============================================================
# TASK 1 — BUBBLE CHART
# ============================================================
import plotly.express as px
# Translate the required categories for display
def task1_category_label(category):
    translations = {
        "BEAUTY": "सुंदरता",      # Hindi
        "BUSINESS": "வணிகம்",     # Tamil
        "DATING": "Dating"        # German
    }
    
    return translations.get(
        category,
        category.replace("_", " ").title()
    )


task1_data["Category_Display"] = (
    task1_data["Category"].apply(task1_category_label)
)


# Create bubble chart
fig = px.scatter(
    task1_data,
    
    # X-axis = App Size
    x="Size_MB",
    
    # Y-axis = Average Rating
    y="Rating",
    
    # Bubble size = Number of Installs
    size="Installs",
    
    # Bubble colour = Category
    color="Category_Display",
    
    # App name shown on hover
    hover_name="App",
    
    hover_data={
        "Size_MB": ":.2f",
        "Rating": ":.2f",
        "Installs": ":,.0f",
        "Reviews": ":,.0f",
        "Avg_Subjectivity": ":.2f",
        "Category_Display": True
    },
    
    title="Task 1: App Size vs Average Rating",
    
    labels={
        "Size_MB": "App Size (MB)",
        "Rating": "Average Rating",
        "Installs": "Number of Installs",
        "Category_Display": "Category"
    },
    
    size_max=55,
    
    # Highlight GAME category in pink
    color_discrete_map={
        "Game": "pink"
    }
)


# Clean layout
fig.update_layout(
    template="plotly_white"
)

# ============================================================
# TASK 1 — DISPLAY ONLY BETWEEN 5 PM AND 7 PM IST
# ============================================================

from datetime import datetime
from zoneinfo import ZoneInfo

current_time = datetime.now(
    ZoneInfo("Asia/Kolkata")
).time()

start_time = current_time.replace(hour=17, minute=0, second=0)
end_time = current_time.replace(hour=19, minute=0, second=0)

if start_time <= current_time < end_time:
    fig.show()
else:
    print(
        "Task 1 Bubble Chart is available only between "
        "5:00 PM and 7:00 PM IST."
    )

Task 1 Bubble Chart is available only between 5:00 PM and 7:00 PM IST.

In [31]:
# TASK 2 – Check available geographic data

print("Current dataset columns:")
print(apps.columns.tolist())

print("\nColumns containing country/region/location:")
geo_columns = [
    col for col in apps.columns
    if any(word in col.lower() for word in ["country", "region", "location", "geo"])
]
print(geo_columns)

print("\nFiles available in the current folder:")
import os
print(os.listdir())

print("\nGeoJSON files:")
geojson_files = [
    file for file in os.listdir()
    if file.lower().endswith(".geojson") or file.lower().endswith(".json")
]
print(geojson_files)

Current dataset columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver', 'Size_MB']

Columns containing country/region/location:
[]

Files available in the current folder:
['.ipynb_checkpoints', 'Analysis.ipynb', 'Analysis2.ipynb', 'Analysis3.ipynb', 'Global EV Data 2024.csv', 'Google_Playstore_Data.ipynb', 'heart-disease.csv', 'My Music', 'My Pictures', 'My Videos', 'Play Store Data.csv.xlsx', 'README.md.txt', 'Untitled.ipynb', 'Untitled1.ipynb', 'User Reviews.csv']

GeoJSON files:
[]

In [32]:
# ============================================================
# TASK 2 - INTERACTIVE PLOTLY CHOROPLETH MAP
# Global App Installs by Category
# Display only between 6 PM and 8 PM IST
# ============================================================

import pandas as pd
import plotly.express as px
from datetime import datetime
from zoneinfo import ZoneInfo
import os

# ------------------------------------------------------------
# 1. Check the current dataset
# ------------------------------------------------------------

print("Task 2 - Dataset check")
print("=" * 50)

print("Rows:", len(apps))
print("Columns:")
print(apps.columns.tolist())

# ------------------------------------------------------------
# 2. Check for country/location information
# ------------------------------------------------------------

location_columns = [
    col for col in apps.columns
    if any(word in col.lower()
           for word in ["country", "region", "location", "continent"])
]

print("\nCountry/Region/Location columns found:")
print(location_columns)

# ------------------------------------------------------------
# 3. Check for GeoJSON files
# ------------------------------------------------------------

geojson_files = [
    file for file in os.listdir()
    if file.lower().endswith(".geojson")
    or file.lower().endswith(".json")
]

print("\nGeoJSON/JSON files found:")
print(geojson_files)

# ------------------------------------------------------------
# 4. Apply Task 2 category requirements
# ------------------------------------------------------------

task2_data = apps.copy()

# Remove missing values required for analysis
task2_data = task2_data.dropna(
    subset=["App", "Category", "Installs"]
).copy()

# ------------------------------------------------------------
# 5. Remove categories beginning with A, C, G or S
# ------------------------------------------------------------

task2_data = task2_data[
    ~task2_data["Category"]
    .astype(str)
    .str.upper()
    .str.startswith(("A", "C", "G", "S"))
].copy()

# ------------------------------------------------------------
# 6. Keep apps with more than 1 million installs
# ------------------------------------------------------------

task2_data = task2_data[
    task2_data["Installs"] > 1_000_000
].copy()

print("\nRows after Task 2 filters:", len(task2_data))

# ------------------------------------------------------------
# 7. Find the TOP 5 APP CATEGORIES
# ------------------------------------------------------------

top_categories = (
    task2_data.groupby("Category")["Installs"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

print("\nTop 5 categories:")
print(top_categories)

# Keep only top 5 categories
task2_data = task2_data[
    task2_data["Category"].isin(top_categories.index)
].copy()

print("\nCategories remaining:")
print(task2_data["Category"].value_counts())

# ------------------------------------------------------------
# 8. Prepare category-level install data
# ------------------------------------------------------------

category_installs = (
    task2_data.groupby("Category", as_index=False)["Installs"]
    .sum()
    .sort_values("Installs", ascending=False)
)

print("\nCategory-level install totals:")
print(category_installs)

# ------------------------------------------------------------
# 9. IMPORTANT ANOMALY CHECK
# ------------------------------------------------------------

if len(location_columns) == 0:
    
    print("\n" + "=" * 60)
    print("ANOMALY DETECTED")
    print("=" * 60)
    
    print(
        "\nThe Google Play Store dataset does not contain "
        "a country, region, or location column."
    )
    
    print(
        "\nA GeoJSON file is also not available in the current "
        "Jupyter folder."
    )
    
    print(
        "\nTherefore, country-level Choropleth mapping cannot "
        "be created from the supplied dataset without inventing "
        "geographic information."
    )
    
    print(
        "\nAccording to the guidance received from ElevanceSkills, "
        "this anomaly should be mentioned in the internship report."
    )
    
    print("\nTask 2 data preparation completed successfully.")
    print("Country-level mapping requires geographic data.")

else:
    
    print("\nLocation information detected.")
    
    # --------------------------------------------------------
    # 10. Prepare country-level data
    # --------------------------------------------------------
    
    location_col = location_columns[0]
    
    print("Using location column:", location_col)
    
    country_data = (
        task2_data.groupby(
            [location_col, "Category"],
            as_index=False
        )["Installs"]
        .sum()
    )
    
    # Keep only records above 1 million installs
    country_data = country_data[
        country_data["Installs"] > 1_000_000
    ].copy()
    
    print("\nCountry-level data prepared:")
    print(country_data.head())

    # --------------------------------------------------------
    # 11. Check GeoJSON
    # --------------------------------------------------------
    
    if len(geojson_files) == 0:
        
        print("\nANOMALY:")
        print(
            "Location data exists, but no GeoJSON file was "
            "found in the current folder."
        )
        
        print(
            "\nPlease mention this limitation in the internship report."
        )
        
    else:
        
        geojson_file = geojson_files[0]
        
        print("\nUsing GeoJSON file:", geojson_file)
        
        # ----------------------------------------------------
        # 12. Create interactive Choropleth
        # ----------------------------------------------------
        
        fig = px.choropleth(
            country_data,
            locations=location_col,
            locationmode="country names",
            color="Installs",
            hover_name=location_col,
            hover_data=["Category", "Installs"],
            color_continuous_scale="Viridis",
            title="Global App Installs by Category"
        )
        
        fig.update_layout(
            title_x=0.5,
            template="plotly_white"
        )
        
        # ----------------------------------------------------
        # 13. Display only between 6 PM and 8 PM IST
        # ----------------------------------------------------
        
        current_time = datetime.now(
            ZoneInfo("Asia/Kolkata")
        ).time()
        
        start_time = current_time.replace(
            hour=18,
            minute=0,
            second=0,
            microsecond=0
        )
        
        end_time = current_time.replace(
            hour=20,
            minute=0,
            second=0,
            microsecond=0
        )
        
        if start_time <= current_time < end_time:
            
            fig.show()
            
        else:
            
            print(
                "\nTask 2 Choropleth Map is available only "
                "between 6:00 PM and 8:00 PM IST."
            )

Task 2 - Dataset check
==================================================
Rows: 10355
Columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver', 'Size_MB']

Country/Region/Location columns found:
[]

GeoJSON/JSON files found:
[]

Rows after Task 2 filters: 1555

Top 5 categories:
Category
PRODUCTIVITY        1.239500e+10
TOOLS               1.132500e+10
FAMILY              9.685000e+09
PHOTOGRAPHY         9.660000e+09
TRAVEL_AND_LOCAL    6.315000e+09
Name: Installs, dtype: float64

Categories remaining:
Category
FAMILY              362
TOOLS               188
PHOTOGRAPHY         161
PRODUCTIVITY        124
TRAVEL_AND_LOCAL     71
Name: count, dtype: int64

Category-level install totals:
           Category      Installs
2      PRODUCTIVITY  1.239500e+10
3             TOOLS  1.132500e+10
0            FAMILY  9.685000e+09
1       PHOTOGRAPHY  9.660000e+09
4  TRAVEL_AND_LOCAL  6.315000e+09

============================================================
ANOMALY DETECTED
============================================================

The Google Play Store dataset does not contain a country, region, or location column.

A GeoJSON file is also not available in the current Jupyter folder.

Therefore, country-level Choropleth mapping cannot be created from the supplied dataset without inventing geographic information.

According to the guidance received from ElevanceSkills, this anomaly should be mentioned in the internship report.

Task 2 data preparation completed successfully.
Country-level mapping requires geographic data.

In [33]:
# ============================================================
# TASK 3 - TIME SERIES LINE CHART
# Total Installs Over Time by App Category
# Available only between 6 PM and 9 PM IST
# ============================================================

import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
from zoneinfo import ZoneInfo

# ------------------------------------------------------------
# 1. Make a copy of the cleaned dataset
# ------------------------------------------------------------

task3_data = apps.copy()

# ------------------------------------------------------------
# 2. Make sure Last Updated is datetime
# ------------------------------------------------------------

task3_data["Last Updated"] = pd.to_datetime(
    task3_data["Last Updated"],
    errors="coerce"
)

# ------------------------------------------------------------
# 3. Remove rows with missing required values
# ------------------------------------------------------------

task3_data = task3_data.dropna(
    subset=["App", "Category", "Reviews", "Installs", "Last Updated"]
).copy()

# ------------------------------------------------------------
# 4. Apply Task 3 filters
# ------------------------------------------------------------

# Reviews greater than 500
task3_data = task3_data[
    task3_data["Reviews"] > 500
].copy()

# App name must NOT start with X, Y or Z
task3_data = task3_data[
    ~task3_data["App"]
    .astype(str)
    .str.upper()
    .str.startswith(("X", "Y", "Z"))
].copy()

# App name must NOT contain the letter S
task3_data = task3_data[
    ~task3_data["App"]
    .astype(str)
    .str.contains("S", case=False, na=False)
].copy()

# App category must start with E, C or B
task3_data = task3_data[
    task3_data["Category"]
    .astype(str)
    .str.upper()
    .str.startswith(("E", "C", "B"))
].copy()

# ------------------------------------------------------------
# 5. Create monthly period
# ------------------------------------------------------------

task3_data["Month"] = (
    task3_data["Last Updated"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

# ------------------------------------------------------------
# 6. Calculate total installs by month and category
# ------------------------------------------------------------

monthly_data = (
    task3_data
    .groupby(["Month", "Category"], as_index=False)["Installs"]
    .sum()
    .sort_values(["Category", "Month"])
)

# ------------------------------------------------------------
# 7. Calculate month-over-month growth
# ------------------------------------------------------------

monthly_data["MoM_Growth"] = (
    monthly_data
    .groupby("Category")["Installs"]
    .pct_change() * 100
)

# ------------------------------------------------------------
# 8. Translate categories for graph display
# ------------------------------------------------------------

category_translation = {
    "BEAUTY": "सौंदर्य",          # Hindi
    "BUSINESS": "வணிகம்",         # Tamil
    "DATING": "Partnersuche"      # German
}

monthly_data["Display_Category"] = (
    monthly_data["Category"]
    .map(category_translation)
    .fillna(monthly_data["Category"])
)

# ------------------------------------------------------------
# 9. Display filtered information
# ------------------------------------------------------------

print("Task 3 data prepared successfully!")
print("=" * 55)

print("\nRows after all Task 3 filters:")
print(len(task3_data))

print("\nCategories remaining:")
print(task3_data["Category"].value_counts())

print("\nMonthly data sample:")
print(monthly_data.head(10))

# ------------------------------------------------------------
# 10. Create Plotly time-series chart
# ------------------------------------------------------------

fig = go.Figure()

categories = monthly_data["Category"].unique()

for category in categories:

    category_data = monthly_data[
        monthly_data["Category"] == category
    ].sort_values("Month").copy()

    display_name = category_data["Display_Category"].iloc[0]

    # --------------------------------------------------------
    # Line chart
    # --------------------------------------------------------

    fig.add_trace(
        go.Scatter(
            x=category_data["Month"],
            y=category_data["Installs"],
            mode="lines+markers",
            name=display_name,
            hovertemplate=(
                "<b>Category:</b> " + display_name +
                "<br><b>Month:</b> %{x|%B %Y}" +
                "<br><b>Total Installs:</b> %{y:,.0f}" +
                "<br><b>MoM Growth:</b> %{customdata:.2f}%"
                "<extra></extra>"
            ),
            customdata=category_data["MoM_Growth"]
        )
    )

    # --------------------------------------------------------
    # Shade areas where MoM growth exceeds 20%
    # --------------------------------------------------------

    for i in range(1, len(category_data)):

        previous_row = category_data.iloc[i - 1]
        current_row = category_data.iloc[i]

        growth = current_row["MoM_Growth"]

        if pd.notna(growth) and growth > 20:

            x_values = [
                previous_row["Month"],
                current_row["Month"]
            ]

            y_values = [
                previous_row["Installs"],
                current_row["Installs"]
            ]

            fig.add_trace(
                go.Scatter(
                    x=x_values,
                    y=y_values,
                    mode="lines",
                    line=dict(width=0),
                    fill="tozeroy",
                    fillcolor="rgba(255, 165, 0, 0.20)",
                    name="Growth > 20%",
                    showlegend=False,
                    hoverinfo="skip"
                )
            )

# ------------------------------------------------------------
# 11. Chart formatting
# ------------------------------------------------------------

fig.update_layout(
    title="Task 3: Monthly Install Trends by App Category",
    xaxis_title="Month",
    yaxis_title="Total Installs",
    template="plotly_white",
    hovermode="x unified",
    legend_title="App Category"
)

# ------------------------------------------------------------
# 12. Display only between 6 PM and 9 PM IST
# ------------------------------------------------------------

current_time = datetime.now(
    ZoneInfo("Asia/Kolkata")
).time()

start_time = current_time.replace(
    hour=18,
    minute=0,
    second=0,
    microsecond=0
)

end_time = current_time.replace(
    hour=21,
    minute=0,
    second=0,
    microsecond=0
)

print("\nCurrent IST time:", current_time.strftime("%H:%M:%S"))

if start_time <= current_time < end_time:

    fig.show()

else:

    print(
        "\nTask 3 Time-Series Chart is available only "
        "between 6:00 PM and 9:00 PM IST."
    )

Task 3 data prepared successfully!
=======================================================

Rows after all Task 3 filters:
215

Categories remaining:
Category
COMMUNICATION          74
ENTERTAINMENT          40
BOOKS_AND_REFERENCE    39
EDUCATION              25
BUSINESS               22
COMICS                  7
BEAUTY                  4
EVENTS                  4
Name: count, dtype: int64

Monthly data sample:
        Month             Category    Installs    MoM_Growth  \
46 2018-03-01               BEAUTY      5000.0           NaN
58 2018-06-01               BEAUTY   1000000.0  19900.000000
64 2018-07-01               BEAUTY   1000000.0      0.000000
72 2018-08-01               BEAUTY    100000.0    -90.000000
5  2014-10-01  BOOKS_AND_REFERENCE    500000.0           NaN
6  2014-11-01  BOOKS_AND_REFERENCE   5000000.0    900.000000
10 2015-07-01  BOOKS_AND_REFERENCE  10000000.0    100.000000
18 2016-06-01  BOOKS_AND_REFERENCE     60000.0    -99.400000
21 2016-08-01  BOOKS_AND_REFERENCE    100000.0     66.666667
27 2017-02-01  BOOKS_AND_REFERENCE    100000.0      0.000000

       Display_Category
46              सौंदर्य
58              सौंदर्य
64              सौंदर्य
72              सौंदर्य
5   BOOKS_AND_REFERENCE
6   BOOKS_AND_REFERENCE
10  BOOKS_AND_REFERENCE
18  BOOKS_AND_REFERENCE
21  BOOKS_AND_REFERENCE
27  BOOKS_AND_REFERENCE

Current IST time: 13:55:38

Task 3 Time-Series Chart is available only between 6:00 PM and 9:00 PM IST.

In [34]:
# ============================================================
# TASK 4 - STACKED AREA CHART
# Cumulative App Installs Over Time by Category
# Display only between 4 PM and 6 PM IST
# ============================================================

import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
from zoneinfo import ZoneInfo
import re

# ------------------------------------------------------------
# 1. Create a copy of the cleaned dataset
# ------------------------------------------------------------

task4_data = apps.copy()

# ------------------------------------------------------------
# 2. Make sure required columns have correct data types
# ------------------------------------------------------------

task4_data["Last Updated"] = pd.to_datetime(
    task4_data["Last Updated"],
    errors="coerce"
)

task4_data["Size_MB"] = pd.to_numeric(
    task4_data["Size_MB"],
    errors="coerce"
)

task4_data["Rating"] = pd.to_numeric(
    task4_data["Rating"],
    errors="coerce"
)

task4_data["Reviews"] = pd.to_numeric(
    task4_data["Reviews"],
    errors="coerce"
)

task4_data["Installs"] = pd.to_numeric(
    task4_data["Installs"],
    errors="coerce"
)

# ------------------------------------------------------------
# 3. Remove rows missing required values
# ------------------------------------------------------------

task4_data = task4_data.dropna(
    subset=[
        "App",
        "Category",
        "Rating",
        "Reviews",
        "Size_MB",
        "Installs",
        "Last Updated"
    ]
).copy()

# ------------------------------------------------------------
# 4. Apply Task 4 filters
# ------------------------------------------------------------

# Average rating at least 4.2
task4_data = task4_data[
    task4_data["Rating"] >= 4.2
].copy()

# App name must NOT contain any numbers
task4_data = task4_data[
    ~task4_data["App"]
    .astype(str)
    .str.contains(r"\d", regex=True, na=False)
].copy()

# App category must start with T or P
task4_data = task4_data[
    task4_data["Category"]
    .astype(str)
    .str.upper()
    .str.startswith(("T", "P"))
].copy()

# Reviews greater than 1,000
task4_data = task4_data[
    task4_data["Reviews"] > 1000
].copy()

# App size between 20 MB and 80 MB
task4_data = task4_data[
    task4_data["Size_MB"].between(20, 80, inclusive="both")
].copy()

# ------------------------------------------------------------
# 5. Create monthly data
# ------------------------------------------------------------

task4_data["Month"] = (
    task4_data["Last Updated"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

# ------------------------------------------------------------
# 6. Calculate monthly installs by category
# ------------------------------------------------------------

monthly_installs = (
    task4_data
    .groupby(["Month", "Category"], as_index=False)["Installs"]
    .sum()
    .sort_values(["Category", "Month"])
)

# ------------------------------------------------------------
# 7. Create complete monthly timeline for each category
# ------------------------------------------------------------

if not monthly_installs.empty:

   all_months = pd.date_range(
    start=monthly_installs["Month"].min(),
    end=monthly_installs["Month"].max(),
    freq="MS"
   )
categories = monthly_installs["Category"].unique()

complete_index = pd.MultiIndex.from_product(
    [all_months, categories],
    names=["Month", "Category"]
)

monthly_installs = (
    monthly_installs
    .set_index(["Month", "Category"])
    .reindex(complete_index, fill_value=0)
    .reset_index()
)# ============================================================
# TASK 4 — Calculate cumulative installs by category
# ============================================================

if not monthly_installs.empty:

    # Sort data by category and month
    monthly_installs = monthly_installs.sort_values(
        ["Category", "Month"]
    ).copy()

    # Calculate cumulative installs for each category
    monthly_installs["Cumulative_Installs"] = (
        monthly_installs
        .groupby("Category")["Installs"]
        .cumsum()
    )

    print("Cumulative install calculation completed successfully.")
    
    print("\nTask 4 data sample:")
    print(
        monthly_installs[
            ["Month", "Category", "Installs", "Cumulative_Installs"]
        ].head(10)
    )

Cumulative install calculation completed successfully.

Task 4 data sample:
        Month   Category  Installs  Cumulative_Installs
0  2014-11-01  PARENTING       0.0                  0.0
6  2014-12-01  PARENTING       0.0                  0.0
12 2015-01-01  PARENTING       0.0                  0.0
18 2015-02-01  PARENTING       0.0                  0.0
24 2015-03-01  PARENTING       0.0                  0.0
30 2015-04-01  PARENTING       0.0                  0.0
36 2015-05-01  PARENTING       0.0                  0.0
42 2015-06-01  PARENTING       0.0                  0.0
48 2015-07-01  PARENTING       0.0                  0.0
54 2015-08-01  PARENTING       0.0                  0.0

In [35]:
# ============================================================
# TASK 4 — Prepare translated categories and chart data
# ============================================================

# Translate required categories for the chart legend
category_translation = {
    "TRAVEL_AND_LOCAL": "Voyage et local",   # French
    "PRODUCTIVITY": "Productividad",        # Spanish
    "PHOTOGRAPHY": "写真"                    # Japanese
}

monthly_installs["Display_Category"] = (
    monthly_installs["Category"]
    .map(category_translation)
    .fillna(monthly_installs["Category"])
)

# Create a table for the stacked area chart
area_data = monthly_installs.pivot(
    index="Month",
    columns="Display_Category",
    values="Cumulative_Installs"
).fillna(0)

# Keep months in chronological order
area_data = area_data.sort_index()

print("Task 4 chart data prepared successfully.")

print("\nTranslated categories:")
print(
    monthly_installs[
        ["Category", "Display_Category"]
    ].drop_duplicates().sort_values("Category")
)

print("\nChart data shape:")
print(area_data.shape)

print("\nChart data sample:")
print(area_data.head())

Task 4 chart data prepared successfully.

Translated categories:
           Category Display_Category
0         PARENTING        PARENTING
1   PERSONALIZATION  PERSONALIZATION
2       PHOTOGRAPHY               写真
3      PRODUCTIVITY    Productividad
4             TOOLS            TOOLS
5  TRAVEL_AND_LOCAL  Voyage et local

Chart data shape:
(46, 6)

Chart data sample:
Display_Category  PARENTING  PERSONALIZATION  Productividad  TOOLS  \
Month
2014-11-01              0.0              0.0            0.0    0.0
2014-12-01              0.0              0.0            0.0    0.0
2015-01-01              0.0              0.0            0.0    0.0
2015-02-01              0.0              0.0            0.0    0.0
2015-03-01              0.0              0.0            0.0    0.0

Display_Category  Voyage et local         写真
Month
2014-11-01                    0.0  1000000.0
2014-12-01                    0.0  1000000.0
2015-01-01                    0.0  1000000.0
2015-02-01                    0.0  1000000.0
2015-03-01                    0.0  1000000.0

In [36]:
# ============================================================
# TASK 4 — VERIFY AND CORRECT REQUIRED FILTERS
# ============================================================

task4_check = apps.copy()

# Rating >= 4.2
task4_check = task4_check[
    task4_check["Rating"] >= 4.2
]

# App name must not contain any numbers
task4_check = task4_check[
    ~task4_check["App"].str.contains(r"\d", regex=True, na=False)
]

# Category must start with I or P
task4_check = task4_check[
    task4_check["Category"].str.startswith(("I", "P"), na=False)
]

# Reviews > 1000
task4_check = task4_check[
    task4_check["Reviews"] > 1000
]

# App size between 20 MB and 80 MB
task4_check = task4_check[
    task4_check["Size_MB"].between(20, 80, inclusive="both")
]

print("Task 4 filters corrected successfully.")
print("=" * 55)

print("\nRows after Task 4 filters:")
print(len(task4_check))

print("\nCategories remaining:")
print(task4_check["Category"].value_counts())

print("\nRequired columns missing values:")
print(
    task4_check[
        ["App", "Category", "Rating", "Reviews", "Size_MB", "Installs"]
    ].isna().sum()
)

Task 4 filters corrected successfully.
=======================================================

Rows after Task 4 filters:
84

Categories remaining:
Category
PHOTOGRAPHY        49
PRODUCTIVITY       20
PERSONALIZATION    11
PARENTING           4
Name: count, dtype: int64

Required columns missing values:
App         0
Category    0
Rating      0
Reviews     0
Size_MB     0
Installs    0
dtype: int64

In [37]:
# ============================================================
# TASK 4 — BUILD MONTHLY INSTALL DATA FROM CORRECT FILTERS
# ============================================================

# Create a fresh monthly dataset from the corrected Task 4 data
task4_check = task4_check.copy()

# Convert Last Updated to monthly period
task4_check["Month"] = (
    task4_check["Last Updated"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

# Calculate total installs per month for each category
monthly_task4 = (
    task4_check
    .groupby(["Month", "Category"], as_index=False)["Installs"]
    .sum()
)

# Create a complete monthly timeline
all_months_task4 = pd.date_range(
    start=monthly_task4["Month"].min(),
    end=monthly_task4["Month"].max(),
    freq="MS"
)

categories_task4 = sorted(
    monthly_task4["Category"].unique()
)

complete_index_task4 = pd.MultiIndex.from_product(
    [all_months_task4, categories_task4],
    names=["Month", "Category"]
)

# Fill months with no installs with zero
monthly_task4 = (
    monthly_task4
    .set_index(["Month", "Category"])
    .reindex(complete_index_task4, fill_value=0)
    .reset_index()
)

# Sort chronologically
monthly_task4 = monthly_task4.sort_values(
    ["Category", "Month"]
).reset_index(drop=True)

# Calculate cumulative installs for each category
monthly_task4["Cumulative_Installs"] = (
    monthly_task4
    .groupby("Category")["Installs"]
    .cumsum()
)

# Calculate month-over-month growth
previous_installs_task4 = (
    monthly_task4
    .groupby("Category")["Installs"]
    .shift(1)
)

monthly_task4["MoM_Growth"] = (
    (monthly_task4["Installs"] - previous_installs_task4)
    / previous_installs_task4
) * 100

# Growth from zero is undefined
monthly_task4.loc[
    previous_installs_task4 == 0,
    "MoM_Growth"
] = pd.NA

# Mark growth greater than 25%
monthly_task4["Significant_Growth"] = (
    monthly_task4["MoM_Growth"] > 25
)

print("Task 4 monthly data prepared successfully.")
print("=" * 55)

print("\nRows:")
print(len(monthly_task4))

print("\nCategories:")
print(monthly_task4["Category"].unique())

print("\nDate range:")
print(
    monthly_task4["Month"].min(),
    "to",
    monthly_task4["Month"].max()
)

print("\nMonthly data sample:")
print(monthly_task4.head(12))

Task 4 monthly data prepared successfully.
=======================================================

Rows:
184

Categories:
['PARENTING' 'PERSONALIZATION' 'PHOTOGRAPHY' 'PRODUCTIVITY']

Date range:
2014-11-01 00:00:00 to 2018-08-01 00:00:00

Monthly data sample:
        Month   Category  Installs  Cumulative_Installs  MoM_Growth  \
0  2014-11-01  PARENTING       0.0                  0.0         NaN
1  2014-12-01  PARENTING       0.0                  0.0         NaN
2  2015-01-01  PARENTING       0.0                  0.0         NaN
3  2015-02-01  PARENTING       0.0                  0.0         NaN
4  2015-03-01  PARENTING       0.0                  0.0         NaN
5  2015-04-01  PARENTING       0.0                  0.0         NaN
6  2015-05-01  PARENTING       0.0                  0.0         NaN
7  2015-06-01  PARENTING       0.0                  0.0         NaN
8  2015-07-01  PARENTING       0.0                  0.0         NaN
9  2015-08-01  PARENTING       0.0                  0.0         NaN
10 2015-09-01  PARENTING       0.0                  0.0         NaN
11 2015-10-01  PARENTING       0.0                  0.0         NaN

    Significant_Growth
0                False
1                False
2                False
3                False
4                False
5                False
6                False
7                False
8                False
9                False
10               False
11               False

In [38]:
# ============================================================
# TASK 4 — INTERACTIVE STACKED AREA CHART
# ============================================================

import plotly.graph_objects as go
from datetime import datetime
from zoneinfo import ZoneInfo

# ------------------------------------------------------------
# 1. Category translations required by Task 4
# ------------------------------------------------------------

category_translation = {
    "TRAVEL_AND_LOCAL": "Voyage et local",   # French
    "PRODUCTIVITY": "Productividad",         # Spanish
    "PHOTOGRAPHY": "写真"                     # Japanese
}

monthly_task4["Display_Category"] = monthly_task4["Category"].map(
    lambda x: category_translation.get(x, x)
)

# ------------------------------------------------------------
# 2. Prepare data for stacked area chart
# ------------------------------------------------------------

chart_data_task4 = (
    monthly_task4
    .pivot_table(
        index="Month",
        columns="Display_Category",
        values="Cumulative_Installs",
        aggfunc="sum"
    )
    .fillna(0)
    .sort_index()
)

# ------------------------------------------------------------
# 3. Create Plotly stacked area chart
# ------------------------------------------------------------

fig_task4 = go.Figure()

for category in chart_data_task4.columns:

    fig_task4.add_trace(
        go.Scatter(
            x=chart_data_task4.index,
            y=chart_data_task4[category],
            mode="lines",
            name=category,
            stackgroup="one",
            line=dict(width=1),
            hovertemplate=(
                "<b>%{fullData.name}</b><br>"
                "Month: %{x|%b %Y}<br>"
                "Cumulative Installs: %{y:,.0f}"
                "<extra></extra>"
            )
        )
    )

# ------------------------------------------------------------
# 4. Highlight months where ANY category grew >25%
# ------------------------------------------------------------

significant_months = (
    monthly_task4.loc[
        monthly_task4["Significant_Growth"] == True,
        "Month"
    ]
    .dropna()
    .unique()
)

for month in significant_months:

    month = pd.Timestamp(month)

    next_month = month + pd.offsets.MonthBegin(1)

    fig_task4.add_vrect(
        x0=month,
        x1=next_month,
        fillcolor="orange",
        opacity=0.12,
        line_width=0,
        layer="below"
    )

# ------------------------------------------------------------
# 5. Chart formatting
# ------------------------------------------------------------

fig_task4.update_layout(
    title="Task 4: Cumulative App Installs by Category",
    xaxis_title="Month",
    yaxis_title="Cumulative Installs",
    hovermode="x unified",
    template="plotly_white",
    legend_title="App Category",
    height=650
)

# ------------------------------------------------------------
# 6. Current IST time
# ------------------------------------------------------------

current_time = datetime.now(
    ZoneInfo("Asia/Kolkata")
).time()

start_time = current_time.replace(
    hour=16,
    minute=0,
    second=0,
    microsecond=0
)

end_time = current_time.replace(
    hour=18,
    minute=0,
    second=0,
    microsecond=0
)

# ------------------------------------------------------------
# 7. Display ONLY between 4 PM and 6 PM IST
# ------------------------------------------------------------

if start_time <= current_time < end_time:

    fig_task4.show()

else:

    print(
        "Task 4 Stacked Area Chart is available only between "
        "4:00 PM and 6:00 PM IST."
    )

Task 4 Stacked Area Chart is available only between 4:00 PM and 6:00 PM IST.

In [39]:
# ============================================================
# TASK 5 — DATA PREPARATION
# ============================================================

import pandas as pd
import numpy as np

# 1. Load original Play Store dataset
file_path = "Play Store Data.csv.xlsx"
task5_df = pd.read_excel(file_path)

print("Task 5 dataset loaded successfully!")
print("Rows:", len(task5_df))
print("Columns:")
print(task5_df.columns.tolist())


# ------------------------------------------------------------
# 2. Convert required columns
# ------------------------------------------------------------

task5_df["Rating"] = pd.to_numeric(
    task5_df["Rating"], errors="coerce"
)

task5_df["Reviews"] = pd.to_numeric(
    task5_df["Reviews"], errors="coerce"
)

# Clean Installs column if it contains + or ,
task5_df["Installs"] = (
    task5_df["Installs"]
    .astype(str)
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)

task5_df["Installs"] = pd.to_numeric(
    task5_df["Installs"], errors="coerce"
)


# ------------------------------------------------------------
# 3. Convert Size into Size_MB
# ------------------------------------------------------------

def convert_size_to_mb(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value == "Varies with device":
        return np.nan

    try:
        if value.endswith("M"):
            return float(value[:-1])

        elif value.endswith("k"):
            return float(value[:-1]) / 1024

        else:
            return np.nan

    except:
        return np.nan


task5_df["Size_MB"] = task5_df["Size"].apply(
    convert_size_to_mb
)


# ------------------------------------------------------------
# 4. Convert Last Updated to datetime
# ------------------------------------------------------------

task5_df["Last Updated"] = pd.to_datetime(
    task5_df["Last Updated"],
    errors="coerce"
)


# ------------------------------------------------------------
# 5. Apply Task 5 filters
# ------------------------------------------------------------

task5_filtered = task5_df[
    (task5_df["Rating"] >= 4.0) &
    (task5_df["Size_MB"] >= 10) &
    (task5_df["Last Updated"].dt.month == 1)
].copy()


# ------------------------------------------------------------
# 6. Remove missing required values
# ------------------------------------------------------------

task5_filtered = task5_filtered.dropna(
    subset=[
        "App",
        "Category",
        "Rating",
        "Reviews",
        "Installs",
        "Size_MB",
        "Last Updated"
    ]
)


# ------------------------------------------------------------
# 7. Aggregate by category
# ------------------------------------------------------------

task5_category = (
    task5_filtered
    .groupby("Category", as_index=False)
    .agg(
        Average_Rating=("Rating", "mean"),
        Total_Reviews=("Reviews", "sum"),
        Total_Installs=("Installs", "sum")
    )
)


# ------------------------------------------------------------
# 8. Select Top 10 categories by installs
# ------------------------------------------------------------

task5_category = (
    task5_category
    .sort_values(
        "Total_Installs",
        ascending=False
    )
    .head(10)
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 9. Display results
# ------------------------------------------------------------

print("\nTask 5 data prepared successfully!")
print("=" * 55)

print("\nRows after Task 5 filters:")
print(len(task5_filtered))

print("\nTop 10 categories by total installs:")
print(task5_category)

print("\nMissing values:")
print(
    task5_category[
        [
            "Category",
            "Average_Rating",
            "Total_Reviews",
            "Total_Installs"
        ]
    ].isna().sum()
)

Task 5 dataset loaded successfully!
Rows: 10841
Columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']

Task 5 data prepared successfully!
=======================================================

Rows after Task 5 filters:
131

Top 10 categories by total installs:
          Category  Average_Rating  Total_Reviews  Total_Installs
0           FAMILY        4.395455      4544623.0     182494820.0
1           SPORTS        4.342857      1982017.0     120511000.0
2             GAME        4.313333      2397589.0     115691000.0
3    ENTERTAINMENT        4.250000      1238948.0      51000000.0
4  PERSONALIZATION        4.475000       155996.0      15060000.0
5      PHOTOGRAPHY        4.150000       563720.0      10500000.0
6        LIFESTYLE        4.380000        42809.0       5071000.0
7        EDUCATION        4.400000        57645.0       2000000.0
8         SHOPPING        4.200000        19950.0       2000000.0
9            TOOLS        4.200000         8010.0       1010000.0

Missing values:
Category          0
Average_Rating    0
Total_Reviews     0
Total_Installs    0
dtype: int64

In [40]:
# ============================================================
# TASK 5 — GROUPED BAR CHART
# ============================================================

import plotly.graph_objects as go
from datetime import datetime
import pytz

# ------------------------------------------------------------
# 1. Create grouped bar chart
# ------------------------------------------------------------

fig_task5 = go.Figure()

fig_task5.add_trace(
    go.Bar(
        x=task5_category["Category"],
        y=task5_category["Average_Rating"],
        name="Average Rating",
        yaxis="y1"
    )
)

fig_task5.add_trace(
    go.Bar(
        x=task5_category["Category"],
        y=task5_category["Total_Reviews"],
        name="Total Reviews",
        yaxis="y2"
    )
)


# ------------------------------------------------------------
# 2. Chart layout
# ------------------------------------------------------------

fig_task5.update_layout(
    title="Task 5: Average Rating and Total Reviews by Top 10 Categories",

    xaxis=dict(
        title="App Category"
    ),

    yaxis=dict(
        title="Average Rating",
        side="left",
        range=[0, 5]
    ),

    yaxis2=dict(
        title="Total Reviews",
        side="right",
        overlaying="y"
    ),

    barmode="group",

    legend=dict(
        title="Metrics"
    ),

    template="plotly_white"
)


# ------------------------------------------------------------
# 3. Display only between 3 PM and 5 PM IST
# ------------------------------------------------------------

india = pytz.timezone("Asia/Kolkata")
current_time = datetime.now(india).time()

start_time = datetime.strptime(
    "15:00", "%H:%M"
).time()

end_time = datetime.strptime(
    "17:00", "%H:%M"
).time()


if start_time <= current_time < end_time:

    fig_task5.show()

else:

    print(
        "Task 5 Grouped Bar Chart is available only "
        "between 3:00 PM and 5:00 PM IST."
    )

Task 5 Grouped Bar Chart is available only between 3:00 PM and 5:00 PM IST.

In [41]:
# ============================================================
# TASK 6 — DATA PREPARATION
# Use the dataset already loaded for Task 5
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. Copy the already-loaded original dataset
# ------------------------------------------------------------

task6_df = task5_df.copy()

print("Task 6 dataset loaded successfully!")
print("Rows:", len(task6_df))
print("Columns:")
print(task6_df.columns.tolist())


# ------------------------------------------------------------
# 2. Convert required numeric columns
# ------------------------------------------------------------

task6_df["Rating"] = pd.to_numeric(
    task6_df["Rating"],
    errors="coerce"
)

task6_df["Reviews"] = pd.to_numeric(
    task6_df["Reviews"],
    errors="coerce"
)


# ------------------------------------------------------------
# 3. Clean Installs
# ------------------------------------------------------------

task6_df["Installs"] = (
    task6_df["Installs"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

task6_df["Installs"] = pd.to_numeric(
    task6_df["Installs"],
    errors="coerce"
)


# ------------------------------------------------------------
# 4. Clean Price
# ------------------------------------------------------------

task6_df["Price"] = (
    task6_df["Price"]
    .astype(str)
    .str.replace("$", "", regex=False)
)

task6_df["Price"] = pd.to_numeric(
    task6_df["Price"],
    errors="coerce"
)


# ------------------------------------------------------------
# 5. Convert Size to MB
# ------------------------------------------------------------

def convert_size_to_mb(value):

    value = str(value).strip()

    if value.lower() in ["nan", "null", "none"]:
        return np.nan

    if value.endswith("M"):
        return float(value[:-1])

    if value.endswith("k"):
        return float(value[:-1]) / 1024

    return np.nan


task6_df["Size_MB"] = task6_df["Size"].apply(
    convert_size_to_mb
)


# ------------------------------------------------------------
# 6. Extract Android version
# ------------------------------------------------------------

task6_df["Android_Version"] = (
    task6_df["Android Ver"]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
)

task6_df["Android_Version"] = pd.to_numeric(
    task6_df["Android_Version"],
    errors="coerce"
)


# ------------------------------------------------------------
# 7. Calculate Revenue
# ------------------------------------------------------------

task6_df["Revenue"] = (
    task6_df["Installs"] *
    task6_df["Price"]
)


# ------------------------------------------------------------
# 8. Apply Task 6 filters
# ------------------------------------------------------------

task6_filtered = task6_df[
    (task6_df["Installs"] >= 10000) &
    (task6_df["Revenue"] >= 10000) &
    (task6_df["Android_Version"] > 4.0) &
    (task6_df["Size_MB"] > 15) &
    (task6_df["Content Rating"] == "Everyone") &
    (task6_df["App"].astype(str).str.len() <= 30)
].copy()


# ------------------------------------------------------------
# 9. Top 3 categories by total installs
# ------------------------------------------------------------

top3_categories = (
    task6_filtered
    .groupby("Category")["Installs"]
    .sum()
    .sort_values(ascending=False)
    .head(3)
    .index
    .tolist()
)


task6_filtered = task6_filtered[
    task6_filtered["Category"].isin(top3_categories)
].copy()


# ------------------------------------------------------------
# 10. Free / Paid
# ------------------------------------------------------------

task6_filtered["App_Type"] = np.where(
    task6_filtered["Type"].astype(str).str.upper() == "PAID",
    "Paid",
    "Free"
)


# ------------------------------------------------------------
# 11. Summary data
# ------------------------------------------------------------

task6_summary = (
    task6_filtered
    .groupby(["Category", "App_Type"])
    .agg(
        Average_Installs=("Installs", "mean"),
        Total_Revenue=("Revenue", "sum")
    )
    .reset_index()
)


# ------------------------------------------------------------
# 12. Display results
# ------------------------------------------------------------

print("\n=======================================================")
print("Task 6 data prepared successfully!")
print("=======================================================")

print("\nRows after Task 6 filters:")
print(len(task6_filtered))

print("\nTop 3 categories:")
print(top3_categories)

print("\nFree vs Paid:")
print(task6_filtered["App_Type"].value_counts())

print("\nTask 6 summary:")
print(task6_summary)

print("\nMissing values:")
print(task6_summary.isna().sum())

Task 6 dataset loaded successfully!
Rows: 10841
Columns:
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver', 'Size_MB']

=======================================================
Task 6 data prepared successfully!
=======================================================

Rows after Task 6 filters:
13

Top 3 categories:
['PHOTOGRAPHY', 'FAMILY', 'PERSONALIZATION']

Free vs Paid:
App_Type
Paid    13
Name: count, dtype: int64

Task 6 summary:
          Category App_Type  Average_Installs  Total_Revenue
0           FAMILY     Paid     381428.571429      5578300.0
1  PERSONALIZATION     Paid     670000.000000      1999900.0
2      PHOTOGRAPHY     Paid    1000000.000000     17970000.0

Missing values:
Category            0
App_Type            0
Average_Installs    0
Total_Revenue       0
dtype: int64

In [42]:
# ============================================================
# TASK 6 — DUAL-AXIS CHART
# Create chart only — NO fig_task6.show()
# ============================================================

import plotly.graph_objects as go

# Make a copy of the Task 6 summary data
chart_df = task6_summary.copy()

# Create category + app type labels
chart_df["Category_App_Type"] = (
    chart_df["Category"] + " - " + chart_df["App_Type"]
)

# ------------------------------------------------------------
# Create dual-axis chart
# ------------------------------------------------------------

fig_task6 = go.Figure()

# Average Installs — left Y-axis
fig_task6.add_trace(
    go.Bar(
        x=chart_df["Category_App_Type"],
        y=chart_df["Average_Installs"],
        name="Average Installs",
        yaxis="y"
    )
)

# Total Revenue — right Y-axis
fig_task6.add_trace(
    go.Scatter(
        x=chart_df["Category_App_Type"],
        y=chart_df["Total_Revenue"],
        name="Total Revenue",
        mode="lines+markers",
        yaxis="y2"
    )
)

# ------------------------------------------------------------
# Layout
# ------------------------------------------------------------

fig_task6.update_layout(
    title="Task 6: Average Installs vs Revenue — Top 3 Categories",

    xaxis=dict(
        title="Category / App Type"
    ),

    yaxis=dict(
        title="Average Installs"
    ),

    yaxis2=dict(
        title="Total Revenue ($)",
        overlaying="y",
        side="right"
    ),

    legend=dict(
        title="Metrics"
    ),

    template="plotly_white"
)

print("Task 6 chart created successfully.")

Task 6 chart created successfully.

In [1]:
# ============================================================
# TASK 6 — FINAL IST TIME RESTRICTION
# Chart displayed ONLY between 1:00 PM and 2:00 PM IST
# ============================================================

from datetime import datetime, time
from zoneinfo import ZoneInfo

# Current time in India
current_time = datetime.now(
    ZoneInfo("Asia/Kolkata")
).time()

# Required time window
start_time = time(13, 0)   # 1:00 PM IST
end_time = time(14, 0)     # 2:00 PM IST

# ------------------------------------------------------------
# Display Task 6 chart only during allowed time
# ------------------------------------------------------------

if start_time <= current_time < end_time:

    fig_task6.show()

    print(
        "Task 6 chart displayed successfully."
    )

else:

    print(
        "Task 6 Dual-Axis Chart is available only "
        "between 1:00 PM and 2:00 PM IST."
    )

Task 6 Dual-Axis Chart is available only between 1:00 PM and 2:00 PM IST.